name: Build AFDKO Win32 Python Wheel

on:
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build Py3 Wheel on Windows
    runs-on: ubuntu-latest

    steps:

    - name: Get Latest Release
      id: latestrelease
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        owner: adobe-type-tools
        repo: afdko
        latest: true

    - run: |
        echo "AFDKO is at version: ${{ steps.latestrelease.outputs.tag_name }}, publish at: ${{ steps.latestrelease.outputs.published_at }}"

    - name: Get date & flat tag
      id: date_tag
      run: |
        export DATE=$(echo ${{steps.latestrelease.outputs.published_at}} | cut -c1-10)
        echo $DATE
        export FLAT_TAG=$(echo ${{ steps.latestrelease.outputs.tag_name }} | sed 's/\.//g')
        echo $FLAT_TAG
        echo ::set-output name=TODAY::$DATE
        echo ::set-output name=VERSION::$FLAT_TAG
      shell: bash
      
    - run: echo ${{ steps.date_tag.outputs.VERSION }}, echo ${{ steps.date_tag.outputs.TODAY }}