name: Build AFDKO Win32 Python Wheel

on:
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build Py3 Wheel on Windows
    runs-on: windows-2019

    steps:

    - name: Check Out
      uses: actions/checkout@v2
      with:
        repository: adobe-type-tools/afdko
        fetch-depth: 0  # unshallow fetch for setuptools-scm

    - name: Install Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: x86

    - name: Build Wheel
      uses: pypa/cibuildwheel@v2.3.1
      with:
        output-dir: dist
      env:
        CIBW_BUILD: "cp39-*"
        CIBW_ARCHS_WINDOWS: x86

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheelstorage
        path: ./dist/*
        if-no-files-found: error
        retention-days: 30

  publish_release:
    name: Publish Release
    needs: build_wheel
    runs-on: ubuntu-latest

    steps:

    - name: Get Latest Release
      id: latest
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        owner: adobe-type-tools
        repo: afdko
        latest: true

    - run: |
        echo "AFDKO is at version: ${{ steps.latest.outputs.tag_name }}, publish at: ${{ steps.latest.outputs.published_at }}"

    - uses: actions/checkout@v3
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.latest.outputs.tag_name }}

    - name: Get date & flat tag
      id: date_tag
      run: |
        export DATE=$(echo ${{steps.latest.outputs.published_at}} | cut -c1-10)
        echo $DATE
        export FLAT_TAG=$(echo ${{ steps.latest.outputs.tag_name }} | sed 's/\.//g')
        echo $FLAT_TAG
        echo ::set-output name=TODAY::$DATE
        echo ::set-output name=VERSION::$FLAT_TAG
      shell: bash

    - name: Download Release Assets
      uses: actions/download-artifact@v2
      with:
        name: wheelstorage
        path: dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        body: '[Release Notes](https://github.com/adobe-type-tools/afdko/blob/develop/NEWS.md#${{ steps.date_tag.outputs.VERSION }}-released-${{ steps.date_tag.outputs.TODAY }})'
        prerelease: false
        tag_name: ${{ steps.latest.outputs.tag_name }}
        files: ./dist/*
