name: Build AFDKO Win32 Python Wheel

on:
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build Py3 Wheel on Windows
    runs-on: ubuntu-latest

    steps:

    - name: Get Latest Release
      id: latestrelease
      uses: kaliber5/action-get-release@v1
      with:
        token: ${{ github.token }}
        owner: adobe-type-tools
        repo: afdko
        latest: true
        
    - name: Example of consumption of the output
      env:
        TAGNAME: ${{ steps.latestrelease.outputs.tag_name }}
        CREATEDAT: $(${{ steps.latestrelease.outputs.created_at }}:0:10)
        PUBLISHEDAT: $(${{ steps.latestrelease.outputs.published_at }}:0:10)
      run: |
        echo "tag_name: $TAGNAME, created_at: $CREATEDAT, published_at: $PUBLISHEDAT"
